#!/bin/bash

#########################################################################
#Name: Rushil Karani
#MacID: karanir
#The Bash Assignment
#Looks through a database of US baby names and prints the rank of a name.
#########################################################################

usage(){
	echo "bn <year> <assigned gender: f|F|m|M|b|B>">&2
}

help(){
    echo "Baby Names Utility v1.0.0"
    echo "Overview: Allows users to search for US baby name rankings"
    echo "for a given year and gender. Uses data from the U.S. baby names data."
    echo "Usage: bn <year> <assigned gender: f|F|m|M|b|B>"
    echo "  <year>                The year (four digits) for which to retrieve name rankings"
    echo "  <assigned gender>     f|F|m|M|b|B (f for female, m for male, b for both)"
    exit 0
}

rank(){
    local name=$1
    local gender=$2
    local file=$3
    local year=$4

    if [[ $gender =~ ^[fF]$ ]]
    then
    	female_rank=$(grep ",F," "$file" | grep -n -i "^$name,F," | grep -o '^[0-9]*')    

        if [ -n "$female_rank" ]
        then
            echo "$year: $name ranked $female_rank out of $female_total female names."
        else
            echo "$year: $name not found among female names."
        fi
    fi

    if [[ $gender =~ ^[mM]$ ]]
    then
        male_rank=$(grep ",M," "$file" | grep -n -i "^$name,M," | grep -o '^[0-9]*')

        if [ -n "$male_rank" ]
        then
            echo "$year: $name ranked $male_rank out of $male_total male names."
        else
            echo "$year: $name not found among male names."
        fi
    fi

    if [[ $gender =~ ^[bB]$ ]]
    then
        female_rank=$(grep ",F," "$file" | grep -n -i "^$name,F," | grep -o '^[0-9]*')
        male_rank=$(grep ",M," "$file" | grep -n -i "^$name,M," | grep -o '^[0-9]*')

		if [ -n "$male_rank" ]
        then
            echo "$year: $name ranked $male_rank out of $male_total male names."
        else
            echo "$year: $name not found among male names."
        fi
        
		if [ -n "$female_rank" ]
        then
            echo "$year: $name ranked $female_rank out of $female_total female names."
        else
            echo "$year: $name not found among female names."
        fi
    fi
}

if [ "$#" != 2 ]
then
	usage
	exit 1
fi

if [[ $1 == "--help" ]]
then
	help
fi

year="$1"
file="us_baby_names/yob$year.txt"
gender="$2"

if ! [[ $year =~ ^[0-9]{4}$ ]]
then
	echo "Badly formatted year: $year">&2
	usage
	exit 2
fi

if ! [[ $gender =~ ^[fmbFMB]$ ]]
then
    echo "Badly formatted assigned gender: $gender">&2
    usage
    exit 2
fi

if [ ! -f "$file" ]
then
    echo "No data for $year">&2
    exit 4
fi

female_total=$(grep -c ",F," "$file")
male_total=$(grep -c ",M," "$file")

while read line
do
	for name in $line
	do
		if ! [[ $name =~ ^[A-Za-z]+$ ]]
		then
			echo "Badly formatted name: $name">&2
			exit 3
		fi
		rank "$name" "$gender" "$file" "$year"
	done
done


